---
# tasks file for ansible-role-rhn-subscription/
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Check Subscription Status"
  shell: LANG=C subscription-manager list | awk  ' ( $1 == "Status:" ) { print $2 } ' | sort -u
  register: subscription_status
  changed_when: false

- name: "Check for Registration Credentials"
  ansible.builtin.fail:
    msg: "Please provide Registration Credentials for this system!!"
  when: ( subscription_status.stdout != "Subscribed" ) and ( (activation_key is not defined) and ((username is not defined ) or (password is not defined)) )

- name: "Ensure credentials are installed for SpaceWalk server {{ spacewalk_server }}"
  ansible.builtin.package:
    name: "{{ 'http://' + spacewalk_server + '/pub/rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm' }}"
    state: present
    validate_certs: no
  when:
    - '"rhn-org-trusted-ssl-cert-1.0-1.noarch" not in ansible_facts.packages'
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version <= '7'

- name: "Uninstall EPEL repository package (CentOS)"
  ansible.builtin.package:
    name: "epel-release"
    state: absent
  when:
    - subscription_status.stdout != "Subscribed"
    - ansible_distribution == 'CentOS'

- name: "Disable all existing Repositories (CentOS 7)"
  ansible.builtin.yum_repository:
    name: "*"
    state: absent
  notify: yum-clean-metadata
  when:
    - subscription_status.stdout != "Subscribed"
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version <= '7'

- name: "Disable all existing Repositories (CentOS 8)"
  ansible.builtin.dnf:
    disablerepo: "*"
  notify: yum-clean-metadata
  when:
    - subscription_status.stdout != "Subscribed"
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version >= '8'

- name: "Register with Spacewalk Server (CentOS)"
  community.general.rhn_register:
    state: present
    activationkey: "{{ activation_key }}"
    server_url: "https://{{ spacewalk_server }}/XMLRPC"
    sslcacert: /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
  when:
    - subscription_status.stdout != "Subscribed"
    - ansible_distribution == 'CentOS'

- name: "Register with Red Hat Subscription Manager (RHEL)"
  community.general.redhat_subscription:
    state: present
    username: "{{ username }}"
    password: "{{ password }}"
    auto_attach: true
    syspurpose:
      usage: "Production"
      role: "Red Hat Enterprise Server"
      service_level_agreement: "Standard"
  when:
    - subscription_status.stdout != "Subscribed"
    - ansible_distribution == 'RedHat'