---
# tasks file for ansible-role-rhn-subscription/

- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}_{{ansible_distribution_major_version}}.yaml'
        - '{{ansible_distribution}}.yaml'
        - '{{ansible_os_family}}.yaml'
        - default.yaml
      paths:
        - 'vars'

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Include tasks from RedHat playbook"
  ansible.builtin.include_tasks: RedHat.yaml
  when: ansible_facts['distribution'] == 'RedHat'

- name: "Include tasks from CentOS playbook"
  ansible.builtin.include_tasks: CentOS.yaml
  when: ansible_facts['distribution'] == 'CentOS'
